server:
  port: 8085 # Internal port for API Gateway

spring:
  cloud:
    gateway:
      routes:
        # Existing User Service Route Definition (we are adding a filter to it)
        - id: user-service-route
          uri: lb://USER-SERVICE 
          predicates:
            - Path=/api/users/**
          filters:
            # 🚨 NEW RATE LIMITER FILTER 🚨
            - name: RequestRateLimiter
              args:
                # Allows 5 requests per second
                redis-rate-limiter.replenishRate: 5
                # Allows a maximum of 10 requests in a burst
                redis-rate-limiter.burstCapacity: 10
                # References the Java bean we will create in the next step
                key-resolver: '#{@ipKeyResolver}'
