# --- Kubernetes Manifests for the complete Ruberoo Microservices Architecture ---
# FINAL VERSION: Includes imagePullPolicy: Never and Eureka URL fix for all clients.

# -----------------------------------------------------------
# 1. ConfigMap for shared Eureka configuration
# -----------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  EUREKA_SERVICE_URL: http://eureka-server:8761/eureka/

---

# -----------------------------------------------------------
# 2. Secret for MySQL Credentials
# -----------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootmitali
  MYSQL_DATABASE_USER: root
  MYSQL_DATABASE_PASSWORD: rootmitali

---

# -----------------------------------------------------------
# 3. Persistent Volume Claim (PVC) for MySQL Data
# -----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

# -----------------------------------------------------------
# MySQL Database Deployment and Service
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: ruberoo_user_db
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

# -----------------------------------------------------------
# Eureka Discovery Server Deployment and Service
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-server
          image: mitalimd/eureka-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP

---

# -----------------------------------------------------------
# User Service Deployment and Service
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: mitalimd/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVICE_URL
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/ruberoo_user_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

# -----------------------------------------------------------
# Ride Management Service Deployment and Service
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-management-service
  labels:
    app: ride-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-service
  template:
    metadata:
      labels:
        app: ride-service
    spec:
      containers:
        - name: ride-service
          image: mitalimd/ride-management-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVICE_URL
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/ruberoo_ride_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ride-management-service
spec:
  selector:
    app: ride-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

---

# -----------------------------------------------------------
# Tracking Service Deployment and Service
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
  labels:
    app: tracking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-service
          image: mitalimd/tracking-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVICE_URL
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/ruberoo_tracking_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  selector:
    app: tracking-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP

---

# -----------------------------------------------------------
# API Gateway Deployment and External Service (NodePort)
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: api-gateway
          image: mitalimd/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            # FIX 1: Force application to use K8s service name (eureka-server)
            - name: JAVA_TOOL_OPTIONS
              value: -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
            # FIX 2: Enable Discovery Locator
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
              value: "true"
            # FIX 3: Enable lowercase matching
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWERCASE_SERVICE_ID
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085
  type: NodePort
