version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REGISTRY: 008041186656.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_REPO_NAME: ruberoo-user
    IMAGE_TAG: latest
    SERVICE_NAME: ruberoo-user-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - REPOSITORY_URI=$ECR_REGISTRY/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Build started
      - echo Current directory
      - pwd
      - echo Java version
      - java -version
      - echo Maven version
      - mvn --version
      - echo Checking project structure
      - ls -la | head -20
      - |
        if [ -f pom.xml ]; then
          echo Parent pom.xml found
        else
          echo ERROR: Parent pom.xml not found
          exit 1
        fi
  build:
    commands:
      - echo Building Maven project
      - mvn clean package -pl $SERVICE_NAME -am -DskipTests
      - echo Maven build completed
      - echo Checking for JAR file
      - |
        if ls $SERVICE_NAME/target/*.jar 1> /dev/null 2>&1; then
          echo JAR file found
        else
          echo ERROR: JAR file not found
          exit 1
        fi
      - echo Building Docker image
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG -f $SERVICE_NAME/Dockerfile $SERVICE_NAME
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"name":"user-service","imageUri":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - $SERVICE_NAME/target/*.jar
