server:
  port: 8085
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**